services:
  db:
    image: redis:latest
    container_name: data
    ports:
        - "6379:6379"



  app-b:
    build: service_b/app

    container_name: fastapi-b

    environment:
      REDIS_HOST: db
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASS: ${REDIS_PASS}

    ports:
      - "8000:8000"

  app-a:
    build: service_a/app

    container_name: fastapi-a

    ports:
      - "8002:8002"
    environment:
      SERVICE_B_URL: http://app-b:8000


